/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface FinancialHistory {
  cash: number | null;
  code: string;
  created_at: Generated<string>;
  dividend_per_share: number | null;
  earnings_per_share: number | null;
  equity_ratio: number | null;
  id: Generated<string | null>;
  month: number;
  operating_cash_flow: number | null;
  operating_profit: number | null;
  operating_profit_margin: number | null;
  payout_ratio: number | null;
  sales: number | null;
  year: number;
}

export interface Industries {
  id: number;
  name: string;
}

export interface Markets {
  id: number;
  name: string;
}

export interface PortfolioItems {
  code: string | null;
  created_at: Generated<string>;
  shares: Generated<number>;
}

export interface Scores {
  cash: Generated<number | null>;
  code: string;
  dividend_per_share: Generated<number | null>;
  earnings_per_share: Generated<number | null>;
  equity_ratio: Generated<number | null>;
  operating_cash_flow: Generated<number | null>;
  operating_profit_margin: Generated<number | null>;
  payout_ratio: Generated<number | null>;
  sales: Generated<number | null>;
  total: Generated<number | null>;
  updated_at: Generated<string>;
}

export interface Stocks {
  code: string;
  created_at: Generated<string>;
  dividend_yield: number | null;
  industry: number | null;
  is_excluded: Generated<number>;
  market: number | null;
  name: string;
  price: number | null;
  updated_at: Generated<string>;
}

export interface StocksWithScores {
  cash_score: number | null;
  code: string;
  dividend_per_share_score: number | null;
  dividend_yield: number | null;
  earnings_per_share_score: number | null;
  equity_ratio_score: number | null;
  industry_id: number | null;
  industry_name: string | null;
  market_id: number | null;
  market_name: string | null;
  name: string;
  operating_cash_flow_score: number | null;
  operating_profit_margin_score: number | null;
  payout_ratio_score: number | null;
  price: number | null;
  sales_score: number | null;
  total_score: number | null;
  updated_at: string;
}

export interface StocksWithTotalScore {
  code: string;
  created_at: string;
  dividend_yield: number | null;
  industry_id: number | null;
  industry_name: string | null;
  market_id: number | null;
  market_name: string | null;
  name: string;
  price: number | null;
  total_score: number | null;
  updated_at: string;
}

export interface DB {
  financial_history: FinancialHistory;
  industries: Industries;
  markets: Markets;
  portfolio_items: PortfolioItems;
  scores: Scores;
  stocks: Stocks;
  stocks_with_scores: StocksWithScores;
  stocks_with_total_score: StocksWithTotalScore;
}
